export const info = [
    {
      id: 1,
      vendor_name: "Ansh Bhutani",
      RFI: "YES",
      RFP: "YES",
      RFQ: "YES",
      Selection: "Selected",
      Desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam posuere, eros nec malesuada vestibulum, diam tortor luctus metus, in mollis purus purus vitae justo. Fusce risus ipsum, fermentum vitae aliquam sit amet, hendrerit a magna. Proin purus diam, tincidunt eget elit at, tincidunt pretium nulla. Pellentesque vitae dui vitae dolor rhoncus elementum. Aenean volutpat ultricies purus, eu elementum est auctor id. Curabitur lacus magna, eleifend quis semper nec, accumsan non neque. Nulla facilisi.",
    },
    {
      id: 2,
      vendor_name: "Rodrigo",
      RFI: "NO",
      RFP: "YES",
      RFQ: "NO",
      Selection: "Pending",
      Desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam posuere, eros nec malesuada vestibulum, diam tortor luctus metus, in mollis purus purus vitae justo. Fusce risus ipsum, fermentum vitae aliquam sit amet, hendrerit a magna. Proin purus diam, tincidunt eget elit at, tincidunt pretium nulla. Pellentesque vitae dui vitae dolor rhoncus elementum. Aenean volutpat ultricies purus, eu elementum est auctor id. Curabitur lacus magna, eleifend quis semper nec, accumsan non neque. Nulla facilisi.",
    },
    {
      id: 3,
      vendor_name: "Bhuvaneshwari",
      RFI: "NO",
      RFP: "NO",
      RFQ: "NO",
      Selection: "Rejected",
      Desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam posuere, eros nec malesuada vestibulum, diam tortor luctus metus, in mollis purus purus vitae justo. Fusce risus ipsum, fermentum vitae aliquam sit amet, hendrerit a magna. Proin purus diam, tincidunt eget elit at, tincidunt pretium nulla. Pellentesque vitae dui vitae dolor rhoncus elementum. Aenean volutpat ultricies purus, eu elementum est auctor id. Curabitur lacus magna, eleifend quis semper nec, accumsan non neque. Nulla facilisi.",
    },
    // {
    //   id: 4,
    //   name: "Austin Howell",
    //   phone: "1-568-430-2622",
    //   email: "in.consequat@yahoo.ca",
    //   country: "Colombia",
    //   alphanumeric: "WSH53KUD5DP",
    // },
    // {
    //   id: 5,
    //   name: "Harriet England",
    //   phone: "1-734-321-0237",
    //   email: "aliquet.proin.velit@google.ca",
    //   country: "Nigeria",
    //   alphanumeric: "TWS18YWE8TD",
    // },
  ];